In [32]:
# Goal: figure out what topics received the most citations in a given year
import pandas as pd
import numpy as np

# Open the data
data_str = open('acm1st10000.txt').read()
# data_str = open('C:\\Users\\Ryan\\Documents\\Ohio State\\8th Semester\\ECE 4194.02\\acm.txt', errors='ignore').read()
data_list = data_str.splitlines()

print(data_list[3])
print(len(data_list))
print(data_list[3][2:])
print()

# Create the dataframe
    # title: (string -- should be bag of words vector)
    # authors: (list)
    # year: publishing year (int)
    # venue: journal the paper was published in (string)
    # ind: numeric label/index of this paper (int)
    # ref_indces: identification index of the papers that referenced this paper (string)
    # abstract: (string -- should be bag of words vector ?)
names = ['title', 'authors', 'year', 'venue', 'ind', 'abstract']

#note that we are ignoring ref
empty_row = pd.DataFrame(columns=names)
df = pd.DataFrame(columns=names)


title = "NULL"
authors = "NULL"
year = "NULL"
venue = "NULL"
index = 0
abstract = "NULL"
not1986 = 0

for i in range(len(data_list)):
    if(i%1000 == 0):
        print(i)
    prefix = data_list[i][0:2]
    if prefix == "#*": 
        title = data_list[i][2:]
        continue
    if prefix == "#@":
        authors = data_list[i][2:]
        continue
    if prefix == "#t":
        year = data_list[i][2:]
        continue
    if prefix == "#c":
        venue = data_list[i][2:]
        continue
    if prefix == "#!":
        abstract = data_list[i][2:]
    if not data_list[i]: #check for the empty string (new article)
        if year == "1986":
#             df = df.append(empty_row)

#             df.at[index,'title'] = title
#             df.at[index,'authors'] = authors
#             df.at[index,'year'] = year
#             df.at[index,'venue'] = venue
#             df.at[index,'abstract'] = abstract

#             title = "NULL"
#             authors = "NULL"
#             year = "NULL"
#             venue = "NULL"
#             abstract = "NULL"
            index += 1

print("Done")
    
# T0-DO:
# -----------------------------------------------------------
# Force strings in dataframe that we want as ints to be ints
# Convert the strings in dataframe to bag of words vectors 
# Make a dataframe of just 2015 papers

# Account for no citations in a dataframe (if citation column is NaN, make it 0)
# Account for no abstract (if abstract column is NaN, remove the row completely)

#index1
69176
ndex1

0
1000
2000
3000
4000
5000
6000
7000
8000
9000
10000
11000
12000
13000
14000
15000
16000
17000
18000
19000
20000
21000
22000
23000
24000
25000
26000
27000
28000
29000
30000
31000
32000
33000
34000
35000
36000
37000
38000
39000
40000
41000
42000
43000
44000
45000
46000
47000
48000
49000
50000
51000
52000
53000
54000
55000
56000
57000
58000
59000
60000
61000
62000
63000
64000
65000
66000
67000
68000
69000
Done

In [29]:
df.head()

,title,authors,year,venue,ind,abstract
0,The INGRES papers: anatomy of a relational dat...,Michael Stonebraker,1986,The INGRES papers: anatomy of a relational dat...,0,A systolic binary tree machine which can handl...
1,The design and implementation of INGRES,"Michael Stonebraker, Peter Kreps, Eugene Wong,...",1986,The INGRES papers: anatomy of a relational dat...,1,NULL
2,Retrospection on a database system,Michael Stonebraker,1986,The INGRES papers: anatomy of a relational dat...,2,NULL
3,The commercial INGRES epilogue,"Lawrence A. Rowe, Michael Stonebraker",1986,The INGRES papers: anatomy of a relational dat...,3,NULL
4,Locking granularity revisited,"Daniel R. Ries, Michael Stonebraker",1986,The INGRES papers: anatomy of a relational dat...,4,NULL